[package]
name = "interactions"
version = "0.1.0"
edition = "2021"

[dependencies]
twilight-http = { default-features = false, features = ["rustls-native-roots", "simd-json", "native"], version = "0.15.2" }

[build]
rustflags = ["-C", "target-cpu=native"]